---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CATALOG_APP_NAME
    value: ${CATALOG_APP_NAME}
  jobs:
  - name: Blue/Green Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      # Create CF services
      cf create-service cloudantNoSQLDB Lite insurance-policy-db
      # Set app's env vars
      domain=".mybluemix.net"
      case "${REGION_ID}" in
        ibm:yp:eu-gb)
          domain=".eu-gb.mybluemix.net"
        ;;
        ibm:yp:au-syd)
        domain=".au-syd.mybluemix.net"
        ;;
      esac
      if ! cf app $CF_APP; then
        cf push $CF_APP -n $CF_APP --no-start
        cf bind-service $CF_APP insurance-policy-db
        cf set-env $CF_APP CATALOG_URL https://$CATALOG_APP_NAME$domain
        cf start $CF_APP
      else
        OLD_CF_APP=${CF_APP}-OLD-$(date +"%s")
        rollback() {
          set +e
          if cf app $OLD_CF_APP; then
            cf logs $CF_APP --recent
            cf delete $CF_APP -f
            cf rename $OLD_CF_APP $CF_APP
          fi
          exit 1
        }
        set -e
        trap rollback ERR
        cf rename $CF_APP $OLD_CF_APP
        cf push $CF_APP -n $CF_APP --no-start
        cf set-env $CF_APP CATALOG_URL https://$CATALOG_APP_NAME$domain
        cf start $CF_APP
        cf delete $OLD_CF_APP -f
      fi
